name: Testing the flow
favicon: null
layout_spectrum: 0.06098960852250457
typography_spectrum: 0.7308202104177326
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6960059127304703
  lightness: 0.06565320491790771
  saturation: 0.7403768326621503
  rhythmicContrast: 0.9198889823164791
purpose: []
